### PR TITLE
Add xblock 2.0 support

### PR DESCRIPTION
**Pull request by irtazaakram**
Related to https://github.com/openedx/edx-platform/issues/34440

### CODE REVIEW

**Comment by Anas12091101** [comment]
@irtazaakram, based on my initial understanding, it seems that in the [test_export](https://github.com/mitodl/edx-sga/blob/master/edx_sga/tests/integration_tests.py#L1010) test case, this [line](https://github.com/openedx/edx-platform/blob/master/xmodule/x_module.py#L1566) is being called in the edx-platform, which is removing the xblock-family attribute, leading to the assertion error. Conversely, in the [test_import](https://github.com/mitodl/edx-sga/blob/master/edx_sga/tests/integration_tests.py#L1010) test case, the [line](https://github.com/openedx/edx-platform/blob/master/xmodule/x_module.py#L1578) is invoking the [parse_xml](https://github.com/mitodl/edx-sga/pull/359/files#diff-f20c006c6512a3abad1639bf6b0ed91d5c1f6c2bd458caa636e2e06ee98d2553R184) method of edx-sga with the id-generator, causing the error.

**Comment by irtazaakram** [comment]
Thanks for looking into this @Anas12091101. Seems like a circular dependency. We are updating xblock https://github.com/openedx/edx-platform/pull/34398/files#diff-f82cb2116924880209a8846a4a84aee3f70301cb682fed8e05a987103da61c9a here that depends on this change here.

What are our options here

**Comment by Anas12091101** [comment]
@irtazaakram I have tested it locally. LGTM. Can you tell me how long is it expected to merge your edx-platform PR?

**Review by Anas12091101 — APPROVED** [review]
Tests are failing but this is required as per @irtazaakram because they need a new release

**Comment by irtazaakram** [comment]
@Anas12091101 PR should be merged as early as possible. I'll let you know as soon its ready.

**Pull request merged**
