### PR TITLE
Add actions cell to assignments table header.

### PR DESCRIPTION
**Pull request by jamiefolsom**
Cosmetic. Makes the assignments table look slightly cleaner.

### CODE REVIEW

**Comment by jamiefolsom** [comment]
Addresses #120.

**Comment by noisecapella** [comment]
You should edit the description of this PR to say 'Fixes #120' instead since Github recognizes strings like those to automatically close issues.

**Comment by jamiefolsom** [comment]
Right, I didn't want to close that issue because it wasn't clear to me whether others agreed with this change. It does seem minor and uncontroversial, which is why I submitted both the issue and the PR without first running any of it by anyone else.

**Comment by noisecapella** [comment]
Looks good to me

**Comment by jamiefolsom** [comment]
Thanks!

**Pull request merged**
