### PR TITLE
Cleaned up zip file creation and retrieval code

### LINKED ISSUE #215: Clean up code related to submission zip creation and downloading
There are many issues with the current code that handles zip creation and downloading, both functionality- and style-related. Among them:

- Submission files are being copied from one directory to another before being compressed, and they almost definitely do not need to be
- When there are no finalized submissions, clicking "Download All Submissions" indicates to the user that the zip file is being created, then nothing happens. We should instead disable the button in these cases, or if that's not possible/performant, we should notify the user that no submissions are available to download
- The source & target paths of the submission files and zip files should be reconsidered, and the way these paths are constructed is confusing
- The forked logic (local storage vs. S3 storage) for creating the submission zip file is probably not necessary
- Logging is basically non-existent. We should add logging in a few different places, particularly where we're writing to files.

We also have a solution in place where the entire contents of each submission file need to be loaded into memory in order to add them to the compressed file. We're using a standard library module (`zipfile`) which makes that unavoidable. This is probably OK for now, but we should look into ways that we can create a compressed file via file chunks.

### PR DESCRIPTION
**Pull request by gsidebo**
#### What are the relevant tickets?
Closes #215 

#### What's this PR do?
Cleans up tech debt around the creation and retrieval of the submission zip file

#### How should this be manually tested?
Test that the "Download All Submissions" button functionality still works as expected

#### Where should the reviewer start?
Probably `edx_sga/tasks.py` (it might be better to look at the file on its own - the diff is a bit messy)

### CODE REVIEW

**Comment by pdpinch** [comment]
@amir-qayyum-khan or @annagav can you review this?

**Comment by amir-qayyum-khan** [comment]
Not able to download zip but UI says it is ready, **docker devstack**.

screen shot 2018-01-17 at 6 13 53 pm

**Comment by gsidebo** [comment]
I'll take a look

**Comment by gsidebo** [comment]
@amir-qayyum-khan I am able to create and download the zip file using both local file storage and S3 storage. Are you clicking "Download All Submissions" a second time after the message says "Student submission file ready for download"? If you are, is that click not doing anything. Please let me know what is happening in your LMS logs after that second click

**Comment by gsidebo** [comment]
@amir-qayyum-khan Ready to review again

**Comment by amir-qayyum-khan** [comment]
i dont know why, i am not able to download zip on docker

**Comment by amir-qayyum-khan** [comment]
can you test it on docker at mitx,may be @annagav machine

**Comment by gsidebo** [comment]
What `edx-platform` branch are you using? Does it work when you try the same with the edx-sga master branch?

**Comment by gsidebo** [comment]
@amir-qayyum-khan I ask that question because the "Download All Submissions" functionality was added to the `mitx/ginkgo` branch. I have never been able to run that branch using Docker-based devstack. If you are seeing any error messages, please paste them here, and if you are actually running the `mitx/ginkgo` branch using Docker, it would be very helpful if you documented the steps you took to make that possible

**Comment by amir-qayyum-khan** [comment]
> What edx-platform branch are you using? Does it work when you try the same with the edx-sga master branch?

Lastest edx master @gsidebo

**Comment by gsidebo** [comment]
@amir-qayyum-khan Can you successfully download the zip file using the `edx-platform` master branch and the `edx-sga` master branch?

**Comment by gsidebo** [comment]
@amir-qayyum-khan I ran the Docker-ized devstack using the `edx-platform` master branch and this `edx-sga` branch, and I was able to successfully download the zip file. If your only remaining issue with this PR is not being able to download the zip file, I think we should merge this and test on QA (cc: @pdpinch)

**Pull request merged**
