### PR TITLE
Changes to use transifex

### PR DESCRIPTION
**Pull request by morenol**
https://github.com/mitodl/edx-sga/pull/259

I made the changes needed to integrate this with transifex but I don't have permissions to run 
`tx push -s`

I added to the Makefile _validate_translations_  and I am using that in the tests to verify if the translations are OK.

The actual update of the strings can be tested by using this version on the devstack using the "eo" language and notice that the string Download All Submissions is now translated.

I changed i18n-tools extract with django-admin makemessages because the metadata generated with the i18n-tools command does not pass the tests. This was also done in https://github.com/edx/edx-ora2/blob/e0e56ac6bc054b7cd71c5e10c8cb99592511cac9/Makefile#L80

### CODE REVIEW

**Comment by pdpinch** [comment]
@morenol how can we manually test this?

**Comment by asadiqbal08** [comment]
How can we test this, any instructions/steps for initial guidance over it ?

**Comment by umarmughal824** [comment]
@pdpinch How can we test this, any instructions/steps for initial guidance over it ?

**Comment by pdpinch** [comment]
The author, @morenol updated the description some time ago with instructions. 

I've never tried changing the translations of edX myself. Does this section of the edX developer guide help? https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/internationalization/i18n.html?highlight=set%20the%20language#coverage-testing

**Comment by morenol** [comment]
I am sorry, with this PR my intention was to upload the translations of this project to the [xblock section](https://www.transifex.com/open-edx/xblocks/content/) of openedx in transifex. 

Since I don't have permissions to push the translations there I am not sure how we can proceed with this. 

Maybe it would be better to keep this PR with only the changes to the Makefile, test_requirements.txt, .tx/config. And then in a separate PR you add the translations by running the command. `make extract_translations`. Regarding to the push process I guess that we would need to talk with someone from edX.

As I said, there is a `make validate_translations` command to validate that the translations have a right syntax.  
And a way to test this would be to install this version on the devstack and use it there with the "eo" language, for instance the string "Download All Submissions" is not translated in the main branch. Not sure which another we could test because right now since the other languages does not have translations.

**Comment by umarmughal824** [comment]
@morenol could you resolve that conflicts.

**Pull request closed without merging**
