### PR TITLE
Added focus to file upload error message

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
fixes https://github.com/mitodl/edx-sga/issues/92

#### What's this PR do?
It adds focus to error message. Good for accessibility.

#### How should this be manually tested?
Try to upload very large file and check in accessible mode

@pdpinch 

#### Screenshots (if appropriate)
screen shot 2015-07-15 at 3 21 01 pm

### CODE REVIEW

**Comment by pdpinch** [comment]
@amir-qayyum-khan can you rebase to see if tests pass?

**Comment by tasawernawaz** [comment]
@pdpinch tests are already passed. I have tried to run this on my local machine. Error message was read by the screenreader however error message was not focused. Will message reader solve our problem by just reading the error message without actually focusing it.

**Comment by amir-qayyum-khan** [comment]
rebased @pdpinch

**Comment by pdpinch** [comment]
If the error message is read by the screenreader, that should be sufficient.

**Pull request merged**
