### PR TITLE
Possible fix for copying units with SGA

### LINKED ISSUE #252: Crash when copy sga-block in course structure
Hi, 
on hawthorn.2 you can reproduce this bug:
1. In Studio create block with sga (in any course)
2. Then go to the course structure page (in studio)
3. Then try to copy this block by pushing button "Copy" on the block
4. Getting error
```
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/course.py", line 270, in course_handler
    return course_index(request, CourseKey.from_string(course_key_string))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/course.py", line 657, in course_index
    ) if current_action else None,
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 1016, in bulk_operations
    yield
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/__init__.py", line 192, in bulk_operations
    self._end_bulk_operation(course_id, emit_signals, ignore_case)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/__init__.py", line 286, in _end_bulk_operation
    dirty = self._end_outermost_bulk_operation(bulk_ops_record, structure_key)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/split.py", line 254, in _end_outermost_bulk_operation
    self.db_connection.insert_structure(bulk_write_record.structures[_id], bulk_write_record.course_key)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/mongo_connection.py", line 436, in insert_structure
    self.structures.insert(structure_to_mongo(structure, course_context))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mongodb_proxy.py", line 115, in __call__
    return self.proxied_object(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pymongo/collection.py", line 540, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: u'Staff Graded Assignment'
```
PS: there is no ADVANCED_COMPONENT_TYPES settings in cms/envs/common.py

### PR DESCRIPTION
**Pull request by tasawernawaz**
#### What are the relevant tickets?
Fixes #252 

#### What's this PR do?
replace `ugettext_lazy` with `ugettext` for fix of copying xblock. 

#### How should this be manually tested?

- Create unit with sga problem
- Copy unit.

### CODE REVIEW

**Comment by pdpinch** [comment]
Ok, I'm persuaded. Do you know why the tests don't pass?

**Comment by tasawernawaz** [comment]
@pdpinch I can see a warning message on build 
```
This job ran using the default Python version, which was updated to 3.6 on April 16th, 2019. You can explicitly stay on the previous version by specifying python: 2.7 in your .travis.yml.
```
I am working on it to get fixed.

**Comment by tasawernawaz** [comment]
@pdpinch build issue has been fixed.

**Comment by noisecapella** [comment]
Sorry for the very long delay on reviewing this. I can confirm this fixes the problem.

**Comment by noisecapella** [comment]
It looks like the `ugettext_lazy` change was originally made to fix a test: https://github.com/mitodl/edx-sga/pull/178, originally from this comment https://github.com/mitodl/edx-sga/pull/174#issuecomment-332273404

Since Travis is passing I'm assuming the tests are currently passing for this PR so this change looks good to me. If we have a problem in the future we can investigate and find out which places we need `ugettext` and which need `ugettext_lazy`.

**Pull request merged**
