### PR TITLE
Fixed build error involving jsonfield import in edx-submissions

### PR DESCRIPTION
**Pull request by gsidebo**
#### What are the relevant tickets?
(Required)

#### What's this PR do?
(Required)

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

#### What GIF best describes this PR or how it makes you feel?
(Optional)

### CODE REVIEW

**Comment by gsidebo** [comment]
@ahmed-belal I'm working on a different project at the moment. This build now passes the Python 2.7 build, but still fails the Integration build. Would you be able to take over this PR and try debugging that build failure? I wouldn't be surprised if we just need to pin another library version. If it doesn't work out, we can talk to Peter about priority

**Comment by ahmed-belal** [comment]
@gsidebo I'm not very well acquainted with the way this is setup, there is one thing that does stand out to me. Pytest on the successful job reports this environment:
```
django111 run-test: commands[0] | py.test
============================= test session starts ==============================
platform linux2 -- Python 2.7.15, pytest-4.6.9, py-1.8.1, pluggy-0.13.1
```

Pytest on the failing integration job reports this environment:
```
============================= test session starts ==============================
platform linux -- Python 3.5.2, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
```

The actual job description says it should've been python 2.7
Screenshot 2020-04-24 at 6 08 01 PM

Do you think that might be a problem or should I dig a bit deeper?

**Comment by pdpinch** [comment]
Do you know what eversion of edX the integration tests are using? If it’s the master branch, then it should be on Python 3 (not sure which one) and not Python 2.7.

**Comment by pdpinch** [comment]
Since this is only failing on the integration tests, which don't work currently with edX on Python3, I think we should go ahead and merge this. 

@gsidebo when you get a chance, could you write a few words in the PR description?

**Comment by gsidebo** [comment]
Build is still failing but I'm merging this b/c it fixes some of the build issues

**Pull request merged**
