### PR TITLE
Recreated submissions zip file when student(s) score reset

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
fixes https://github.com/mitodl/edx-sga/issues/224

#### What's this PR do?
It detects if any student has reset score. If yes then it will recreate zip file instead of facilitating old one. 

#### How should this be manually tested?
- Install this branch in edX platform
- download student submisisons
- reset score
- down submissions again
- see contents should update

@pdpinch

### CODE REVIEW

**Comment by pdpinch** [comment]
@amir-qayyum-khan can you rebase to see if tests pass?

**Comment by amir-qayyum-khan** [comment]
@pdpinch rebased

**Comment by amir-qayyum-khan** [comment]
@tasawernawaz

**Comment by tasawernawaz** [comment]
@amir-qayyum-khan taking a look. Do we need to add more test to fix failing coverage ?
CC: @pdpinch

**Comment by amir-qayyum-khan** [comment]
the api that is creating zip file and counting contents are mocked. Thats why coverage of `count_archive_files` which access local storage is missing. I think it is good to go

**Comment by tasawernawaz** [comment]
@amir-qayyum-khan what's the step # 3 "reset score" ? I can't see any change in zip file's name after entering grade.

**Comment by tasawernawaz** [comment]
Learner can only once upload his submission after https://github.com/mitodl/edx-sga/pull/191/.

I can't see there is any way that learner can resubmit his assignment until instructor allows him by deleting his state from instructor dashboard.

@amir-qayyum-khan Given that, I think we can close this PR. @pdpinch please provide your opinion if this PR still worth to merge.

**Comment by amir-qayyum-khan** [comment]
yes, this PR no longer required since we added one time submit button to learner view of sga. Now submission can only be reset from instructor dashboard. I am closing it

**Comment by tasawernawaz** [comment]
I spoke too soon about this, me and @amir-qayyum-khan was doing wrong steps. It still makes sense to me.

**Comment by amir-qayyum-khan** [comment]
oops was testing wrong steps, retested and verified

**Pull request merged**
